name: Announce the release on Slack

on:
  push:
    branches: [main]
    
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get latest commit info
        run: |
          echo "::set-output name=BODY::$(curl -isb -H "Accept: application/json" https://api.github.com/repos/marcositu/prueba/actions/artifacts?per_page=3 |grep archive_download_url)"
        id: latest_commit
      - uses: homeday-de/slack-release-bot-action@main
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          title: PRUEBA
          body: ${{ steps.latest_commit.outputs.BODY }}
          context: Pipeline
