on:
  push:
    branches: [ main ]

  # to run manually
  workflow_dispatch:

jobs:
  ZAP_Scan:
    name: ZAP Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }} // necessary for pull request workflow trigger
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
