name: Announce the release on Slack

on:
  push:
    branches: [main]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get latest commit info
        run: |
          my_string=$(curl -s https://api.github.com/repos/marcositu/prueba/actions/artifacts?per_page=1 | jq '[.artifacts[] |.archive_download_url]' | grep http)
          echo "::set-output name=my_string::$my_string"
        id: latest_commit
      - uses: homeday-de/slack-release-bot-action@main
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          title: "OWASP Dependency Check"
          body: ${{ steps.latest_commit.outputs.my_string }}
          context: Website
