on:
  push:
    branches: [ main ]

  # to run manually
  workflow_dispatch:

jobs:
  ZAP_Scan:
    name: ZAP Scan
    runs-on: ubuntu-latest
    steps:
      - name: Trufflehog scan (SIS)
        uses: edplato/trufflehog-actions-scan@master
