name: Announce the release on Slack

on:
  push:
    branches: [main]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get latest commit info
        run: |
          my_string=$(curl -H "Accept: application/json" https://api.github.com/repos/marcositu/prueba/actions/artifacts?per_page=1 -s)
          my_string="${my_string//'%'/'%25'}"
          my_string="${my_string//$'\n'/'%0A'}"
          my_string="${my_string//$'\r'/'%0D'}"
          echo "::set-output name=my_string::$my_string"
        id: latest_commit
      - uses: homeday-de/slack-release-bot-action@main
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          title: "OWASP Dependency Check"
          body: ${{ steps.latest_commit.outputs.my_string }}
          context: Website
