on:
  push:
    branches: [ main ]

  # to run manually
  workflow_dispatch:

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        port: ${{ secrets.SERVER_PORT }}
        command_timeout: 200m
        script: git clone https://github.com/OWASP/NodeGoat.git ; cd NodeGoat ; docker-compose build ; docker-compose up
