name: Announce the release on Slack

on:
  push:
    branches: [main]
    
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get latest commit info
        run: |
          echo "FOO=$(git status)" >> $GITHUB_ENV
        id: latest_commit
      - uses: homeday-de/slack-release-bot-action@main
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'TERMINO EL PIPELINE'
          body: "${{ env.FOO }}"
          context: Pipeline
